### PR TITLE
GetKeyIndex is nop since 1.87+ and obsoleted from 1.90.5 b

### PR DESCRIPTION
**Pull request by sonoro1234**
include <cmath> for sqrt in TextEditor.h

include <cmath> for sqrt

GetKeyIndex is nop since 1.87+ and obsoleted from 1.90.5

### CODE REVIEW

**Comment by sonoro1234** [comment]
The #27 should be closed!!

**Comment by santaclose** [comment]
ok i just tested your changes, the commit message is currently `cosmetic ((ImGui...)) -> (ImGui...)`, could you change it to something that makes more sense? maybe something like "move cmath header and stop using GetKeyIndex". Commands for this should be `git commit --amend`, then you get a text editor to modify the message, and then `git push origin santa_master_imguikey --force`

**Comment by sonoro1234** [comment]
done.

**Comment by santaclose** [comment]
thanks!

**Pull request merged**
